import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import "../components/styles/globals.css";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html>
//       <body className=" font-sans font-mono bg-black text-white">
//         {children}
//       </body>
//     </html>
//   );
// }
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html>
        <body
          className={`bg-black text-white font-sans overflow-hidden ${geistSans.variable} ${geistMono.variable} `}
        >
          <main>
            <SidebarProvider>
              <AppSidebar />
              <div className="h-screen bg-[#000026] p-2 ">
                <SidebarTrigger className="flex-1  cursor-pointer" />
              </div>
              {children}
            </SidebarProvider>
          </main>
        </body>
      </html>
    </>
  );
}
